### ISSUE TITLE
路由未生效

### ISSUE THREAD

**Issue by SongLin123** [soraping/lenneth#1]
环境：
windows-10，
nodejs-v8.11.1

我通过lenneth-cli构建的项目，服务开启之后控制台输出了

`[2019-02-26T18:15:40.935] [INFO ] [lenneth] - 
┌────────┬────────────────┬────────────────────────┬─────────────┐
│ Method │ Endpoint       │ Class method           │ Description │
│────────│────────────────│────────────────────────│─────────────│
│ GET    │ \apis\test\get │ TestController.getData │ get调试       │
│────────│────────────────│────────────────────────│─────────────│
│ GET    │ \              │ HomeController.getData │             │
└────────┴────────────────┴────────────────────────┴─────────────┘`

但是路由并没生效，望大佬解答。

ps: package.json里的scripts在windows完全不能用......

**Comment by SongLin123** [comment]
没说全...

服务开起来了，监听端口也成功了，但是访问路由只返回了
`{
"code": 0,
"message": "success"
}`
任何代码都没有改过。

**Comment by soraping** [comment]
window和linux是有区别的，`rm` 是linux的命令，win没有，我等下兼容下win

**Comment by SongLin123** [comment]
额，那个不是主要问题。。
主要是路由注入没有生效，cli提供的模板在index.ts里面注入了两条路由，应该都没有生效，只有最后的response包装器生效了。
我console看了一下，在进最后一个中间件之前的response.body是undefine，我不太确定这是什么问题。
谢谢回复！

**Comment by soraping** [comment]
我更新了一个版本，你可以用
```js
ctx.body = ''
```
这个试下看看是否可以
其实ctx.body其实就response.body，ctx代理了response的属性，如果没有好的话，我再拿win10跑下，周围人都是mac，找个win还真不容易

**Comment by SongLin123** [comment]
并没有起作用，我看了你的改动了，应该不是这部分的问题，我把返回值统一处理的部分注释掉之后返回404，应该问题在路由注入的部分上。
话说在mac上能正常使用么？感觉和系统环境应该没什么关系啊

**Comment by soraping** [comment]
找了win试了下，确实不支持，之前没有在win上跑过，周围都是mac，所以没有做这个兼容，我来搞下兼容吧

**Comment by soraping** [comment]
windows 问题已经修复，主要是window的path斜杠的问题，做了兼容，周围一直都用mac，想找window都不容易。。。
