### ISSUE TITLE
命令行工具下载模板失败

### ISSUE THREAD

**Issue by bullub** [soraping/lenneth#2]
执行 `lenneth init project` 时候，报如下错误

下载模版项目git地址 => https://git.coding.net/soraping/lenneth-template.git
<font color="red">
  [2020/6/1] [上午10:19:58] [lenneth] › ✖  error     下载git模版失败
</font>

**Comment by soraping** [comment]
试下 ```git clone https://git.coding.net/soraping/lenneth-template.git```  手动下载，看下是否会报错
我刚拿新机器试了下，没有出现下载报错的问题

**Comment by bullub** [comment]
会的，你这个项目可能是私有的，我访问该链接，响应404.

**Comment by soraping** [comment]
我改了下配置，现在可以了

**Comment by 2234839** [comment]
> 
> 
> 我改了下配置，现在可以了

![图片](https://user-images.githubusercontent.com/28727933/96667488-bac84100-138b-11eb-9b64-5724a362112a.png)
我这依旧不行

**Comment by soraping** [comment]
修改了client工具，更新下就可以了，是git仓库的地址被修改了

**Comment by 2234839** [comment]
> 
> 
> 修改了client工具，更新下就可以了，是git仓库的地址被修改了

![图片](https://user-images.githubusercontent.com/28727933/96668877-adf91c80-138e-11eb-8aea-a385c7b7f20b.png)

**Comment by 2234839** [comment]
> 
> 
> 修改了client工具，更新下就可以了，是git仓库的地址被修改了

可以了
